---
- name: gather operating system variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution_file_variety | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- name: assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This module only works with systemd"
  become: true
  tags: smtp_to_telegram

- name: get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  become: true
  tags: smtp_to_telegram

- name: set systemd version fact
  set_fact:
    smtp_to_telegram_systemd_version: "{{ __systemd_version.stdout_lines[0].split(' ')[-1] }}"
  become: true
  tags: smtp_to_telegram

- name: create system group
  group:
    name: "{{ smtp_to_telegram_system_group }}"
    system: true
    state: present
  when: smtp_to_telegram_system_group != "root"
  become: true
  tags: smtp_to_telegram

- name: create system user
  user:
    name: "{{ smtp_to_telegram_system_user }}"
    system: true
    shell: "/sbin/nologin"
    group: "{{ smtp_to_telegram_system_group }}"
    createhome: false
  when: smtp_to_telegram_system_user != "root"
  become: true
  tags: smtp_to_telegram

- name: check if smtp_to_telegram is installed
  stat:
    path: "{{ smtp_to_telegram_binary_install_dir }}/smtp_to_telegram"
  register: __smtp_to_telegram_is_installed
  become: true
  tags: smtp_to_telegram

- name: gather currently installed smtp_to_telegram version
  command: "{{ smtp_to_telegram_binary_install_dir }}/smtp_to_telegram --version"
  args:
    warn: false
  changed_when: false
  register: __smtp_to_telegram_current_version_output
  when: __smtp_to_telegram_is_installed.stat.exists
  become: true
  tags: smtp_to_telegram

- block:
  - name: get checksum list from github
    set_fact:
      _checksums: "{{ lookup('url', 'https://github.com/OnkelDom/smtp-to-telegram/releases/download/v' + smtp_to_telegram_version + '/checksums.txt', wantlist=True) | list }}"
    environment: "{{ proxy_env }}"
    run_once: true
    become: true
    tags: smtp_to_telegram

  - name: "get checksum for {{ go_arch }} architecture"
    set_fact:
      smtp_to_telegram_checksum: "{{ item.split(' ')[0] }}"
    with_items: "{{ _checksums }}"
    when: "('smtp-to-telegram_' + smtp_to_telegram_version + '_linux_' + go_arch + '.tar.gz') in item"
    become: true
    tags: smtp_to_telegram

  - name: download binary to local folder
    get_url:
      url: "https://github.com/OnkelDom/smtp-to-telegram/releases/download/v{{ smtp_to_telegram_version }}/smtp-to-telegram_{{ smtp_to_telegram_version }}_linux_{{ go_arch }}.tar.gz"
      dest: "/tmp/smtp_to_telegram-{{ smtp_to_telegram_version }}.linux-{{ go_arch }}.tar.gz"
      checksum: "sha256:{{ smtp_to_telegram_checksum }}"
    environment: "{{ proxy_env }}"
    register: _download_archive
    until: _download_archive is succeeded
    retries: 5
    delay: 2
    delegate_to: localhost
    check_mode: false
    become: true
    tags: smtp_to_telegram

  - name: unpack binaries
    unarchive:
      src: "/tmp/smtp_to_telegram-{{ smtp_to_telegram_version }}.linux-{{ go_arch }}.tar.gz"
      dest: "/tmp"
    delegate_to: localhost
    check_mode: false
    become: true
    tags: smtp_to_telegram

  - name: propagate console-templates
    copy:
      src: "/tmp/{{ item }}"
      dest: "{{ smtp_to_telegram_binary_install_dir }}/{{ item }}"
      mode: 0755
      owner: "root"
      group: "root"
    with_items:
      - smtp_to_telegram
    notify: restart smtp_to_telegram
    become: true
    tags: smtp_to_telegram
  when: (not __smtp_to_telegram_is_installed.stat.exists) or (__smtp_to_telegram_current_version_output.stdout.split(" ")[2] != smtp_to_telegram_version)

- name: create systemd service unit
  template:
    src: smtp_to_telegram.service.j2
    dest: /etc/systemd/system/smtp_to_telegram.service
    owner: root
    group: root
    mode: 0644
  notify: restart smtp_to_telegram
  become: true
  tags: smtp_to_telegram

- name: enable capabilities to ports lower than port 1024
  capabilities:
    path: "{{ smtp_to_telegram_binary_install_dir }}/smtp_to_telegram"
    capability: CAP_NET_BIND_SERVICE+ep
    state: present
  when: smtp_to_telegram_listen_port <= 1024
  tags: smtp_to_telegram

- name: install selinux dependencies
  package:
    name: "{{ item }}"
    state: present
  environment: "{{ proxy_env }}"
  with_items: "{{ smtp_to_telegram_selinux_packages }}"
  register: _install_packages
  until: _install_packages is succeeded
  retries: 5
  delay: 2
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
  become: true
  tags: smtp_to_telegram

- name: allow binding to port in selinux
  seport:
    ports: "{{ smtp_to_telegram_listen_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
  become: true
  tags: smtp_to_telegram

- name: check whether ufw status is active
  command: "ufw status"
  changed_when: False
  ignore_errors: True
  register: _ufw_status
  become: true
  when:
    - smtp_to_telegram_allow_firewall
    - ansible_os_family == 'Debian'
  tags: smtp_to_telegram

- name: check whether firewalld status is active
  command: "firewall-cmd --state"
  changed_when: False
  ignore_errors: True
  register: _firewalld_status
  become: true
  when: ansible_os_family == 'RedHat'
  tags: smtp_to_telegram

- name: configure ufw
  community.general.ufw:
    rule: allow
    port: "{{ smtp_to_telegram_listen_port }}"
    proto: tcp
    state: enabled
    comment: "Consul Template"
  changed_when: False
  ignore_errors: True
  notify: reload ufw
  become: true
  tags: smtp_to_telegram
  when:
    - "'active' in _ufw_status.stdout"
    - ansible_os_family == 'Debian'
    - smtp_to_telegram_allow_firewall

- name: configure firewalld
  firewalld:
    port: "{{ smtp_to_telegram_listen_port }}/tcp"
    permanent: yes
    state: true
  changed_when: False
  ignore_errors: True
  when:
    - "'running' in _firewalld_status.stdout"
    - smtp_to_telegram_allow_firewall
    - ansible_os_family == 'RedHat'
  notify: reload firewalld
  become: true
  tags: smtp_to_telegram

- name: ensure smtp_to_telegram service is started and enabled
  systemd:
    daemon_reload: true
    name: smtp_to_telegram
    state: started
    enabled: true
  become: true
  tags: smtp_to_telegram